name: Hello World

on: [push]

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Step 1
        id: greet_step
        run: |
          echo "message=You pushed this code" >> $GITHUB_OUTPUT

      - name: Step 2
        run: echo "Message from previous step: ${{ steps.greet_step.outputs.message }}"
