name: Reply to Issue

on: 
  issues: 
    types: [opened]

permissions: 
  issues: write

jobs:
  comment:
    runs-on: ubuntu-latest

    steps:
      - name: Print Context Object
        uses: actions/github-script@v6
        with:
          script: |
            console.log(context)

      - name: Auto comment Using Github API
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "Thanks for opening the issue, we will look into it!"
            })


      - name: Auto Comment By External Actions
        uses: peter-evans/create-or-update-comment@v4
        with: 
          issue_number: ${{ github.event.issue.number }}
          body: |
            👋 **Thanks for opening this issue!**

            We'll get back to you as soon as possible.
